### ISSUE TITLE
git error when running buffalo setup

### ISSUE THREAD

**Issue by flesh** [mikaelm1/Blog-App-Buffalo#8]
Update: This is a know problem with git and go, you have to delete the go projects that can not be updated; more to the point this is the way git works when the head changes between updates, and needs to be handled in buffalo update so that is another issue unrelated to this project, the API being out of date is another issue so you can close this one, or leave it open for the next new guy to go, I never had this issue till I tried this project, now I have it on my own, irritating and searching the internet for an answer is more frustrating, I lost a whole day thinking it was my setup; great article, can't wait to get it updated.

On a fresh install download or clone, after updating all references to imports and database, I I ran buffalo setup, I get these errors on all pulls: 
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.

I tried deleting the .git, no help, did:
git config --global user.name "user"
git config --global user.email "email@gmail.com"
git init
git reset --hard
git add .
git commit -q -m "Initial Commit"
no help
I also got an out of date error and tried to run buffalo update with same results.
I have no issue running either on other projects.
Running on Manjaro
Maybe you could run buffalo update and commit it back, but I have no idea why this project is giving me this error.
Thanks, great article, just want to see the project, following tutorial the API is out of date also.

**Comment by mikaelm1** [comment]
I just realized that the instructions on my README were wrong (I removed them). Probably best to just follow along with the tutorial and build your project from scratch. I haven't used Go much since I wrote this thing, but if I remember correctly you might be able to get around this by running `go get -u github.com/mikaelm1/Blog-App-Buffalo` since many of the imports in the project rely on this project existing in your GOPATH as a 3rd party library, such as the import in `actions/app.go` - `"github.com/mikaelm1/blog_app/models"`
